name: cure_connect_service
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_bloc: ^8.1.6
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  badges: ^3.1.2
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  firebase_storage: ^12.3.5
  cloud_firestore: ^5.4.5
  firebase_data_connect: ^0.1.2+2
  google_sign_in: ^6.2.2
  flutter_animate: ^4.5.2
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.3
  flutter_stripe: ^11.3.0
  dio: ^5.7.0
  animate_do: ^3.3.4
  intl: ^0.19.0
  get_storage: ^2.1.1
  emoji_picker_flutter: ^3.1.0
  agora_rtc_engine: ^6.5.0
  permission_handler: ^11.3.1
  flutter_rating_bar: ^4.0.1
  flutter_webrtc: ^0.12.5+hotfix.2
  flutter_launcher_icons: ^0.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app logo.jpg 2 (1).png" 
  adaptive_icon_background: "#ffffff"  
  adaptive_icon_foreground: "assets/app logo.jpg 2 (1).png" 

flutter:
  uses-material-design: true
  assets:
    - assets/